'use client'

interface Item {
  id: number,
  name: string,
  description: string,
  price: number,
  year: string,
  fullDescription: string
};

const fullDescriptionTemplate = 'Placeholder Description and Product Name for the Interactive Showcase. This is a temporary product name and description for the featured interactive showcase. It is intended to provide a brief overview of the product and its features. The product is designed to be interactive and engaging, allowing users to explore its capabilities in a hands-on manner. The description may include information about the product';

export const Items: Item[] = [{
  id: 1,
  name: 'Product name for the temporary featured interactive showcase',
  description: 'Placeholder Description and Product Name for the Interactive Showcase',
  price: 299.99,
  year: '2026',
  fullDescription: fullDescriptionTemplate,
},
{
  id: 2,
  name: 'Temporary Product Title and Description for the Featured Showcase',
  description: 'Updated iOS 27 and iPadOS 27 design kit for Figma.',
  price: 499.99,
  year: '2025',
  fullDescription: fullDescriptionTemplate,
},
{
  id: 3,
  name: 'Placeholder Name for the Featured Interactive Showcase',
  description: 'Icon Composer 2 lets you create layered icons out of Liquid Glass from a single design for iPhone, iPad, Mac, and Apple Watch.',
  price: 899.99,
  year: '2024',
  fullDescription: fullDescriptionTemplate,
},
{
  id: 4,
  name: 'Temporary Label for the Featured Interactive Module',
  description: 'Updated iOS 27 and iPadOS 27 design kit for Figma.',
  price: 499.99,
  year: '2025',
  fullDescription: fullDescriptionTemplate,
},
{
  id: 5,
  name: 'Placeholder Title for the Highlighted Interactive Feature',
  description: 'Pass Designer makes it easy to craft and preview Wallet passes that reflect your business.',
  price: 199.99,
  year: '2022',
  fullDescription: fullDescriptionTemplate,
},
{
  id: 6,
  name: 'Temporary Label for the Featured Interactive Module',
  description: 'Pass Designer makes it easy to craft and preview Wallet passes that reflect your business.',
  price: 399.99,
  year: '2022',
  fullDescription: fullDescriptionTemplate,
},
{
  id: 7,
  name: 'Placeholder Title for the Highlighted Interactive Feature',
  description: 'Pass Designer makes it easy to craft and preview Wallet passes that reflect your business.',
  price: 399.99,
  year: '2022',
  fullDescription: fullDescriptionTemplate,
},
{
  id: 8,
  name: 'Temporary Label for the Featured Interactive Module',
  description: 'Pass Designer makes it easy to craft and preview Wallet passes that reflect your business.',
  price: 399.99,
  year: '2022',
  fullDescription: fullDescriptionTemplate,
},
{
  id: 9,
  name: 'Product name for the temporary featured interactive showcase',
  description: 'Pass Designer makes it easy to craft and preview Wallet passes that reflect your business.',
  price: 399.99,
  year: '2022',
  fullDescription: fullDescriptionTemplate,
},
{
  id: 10,
  name: 'Temporary Label for the Featured Interactive Module',
  description: 'Pass Designer makes it easy to craft and preview Wallet passes that reflect your business.',
  price: 399.99,
  year: '2022',
  fullDescription: fullDescriptionTemplate,
},
{
  id: 11,
  name: 'Temporary product name for the featured interactive showcase',
  description: 'Pass Designer makes it easy to craft and preview Wallet passes that reflect your business.',
  price: 399.99,
  year: '2022',
  fullDescription: fullDescriptionTemplate,
},
{
  id: 12,
  name: 'Temporary Label for the Featured Interactive Module',
  description: 'Icon Composer 2 lets you create layered icons out of Liquid Glass from a single design for iPhone, iPad, Mac, and Apple Watch.',
  price: 899.99,
  year: '2024',
  fullDescription: fullDescriptionTemplate,
},
{
  id: 13,
  name: 'Temporary product name for the featured interactive showcase',
  description: 'Icon Composer 2 lets you create layered icons out of Liquid Glass from a single design for iPhone, iPad, Mac, and Apple Watch.',
  price: 899.99,
  year: '2024',
  fullDescription: fullDescriptionTemplate,
}];